# Generated by Django 5.2.1 on 2025-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='menus', to='webapp.category'),
        ),
    ]
