# Generated by Django 5.2.1 on 2025-05-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_facility_room_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='icon_class',
        ),
    ]
