# Generated by Django 5.2.1 on 2025-05-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_gallery',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
