# Generated by Django 5.2.1 on 2025-05-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_room_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image_gallery',
        ),
    ]
