# Generated by Django 5.2.1 on 2025-05-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_room_image_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
