# Generated by Django 5.2.1 on 2025-05-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
