# Generated by Django 5.2.1 on 2025-05-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
    ]
