# Generated by Django 5.1.6 on 2025-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_gallery/'),
        ),
    ]
