"""
Django settings for manahayu project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v*y7$bc9scr(i^@fgr$k%&xs6z&r1m(*57(gc_bst#y5kgnv7c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1','localhost','192.168.181.152']
ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [   
    'http://localhost:8000',  # Sesuaikan dengan port Django Anda
    'http://127.0.0.1:8000',  # Sesuaikan dengan port Django Anda
    'https://*.ngrok.io',
    'http://*.ngrok.io',
    'https://*.ngrok-free.app', # <-- Tambahkan ini
    'http://*.ngrok-free.app',]

# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #Local Apps 
    'webapp',
    'tailwind',
    'theme',
    'django_browser_reload', 
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

INTERNAL_IPS = [
    "127.0.0.1",
]


ROOT_URLCONF = 'manahayu.urls'

TAILWIND_APP_NAME = 'theme'

# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



STATICFILES_DIRS = [ BASE_DIR  / "theme" / "static",]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Pastikan path ini benar
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'manahayu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Config Unfold
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# UNFOLD = {
#     "SITE_TITLE": "Manahayu Administration",
#     "SITE_HEADER": "Django Administration",
#     "SIDEBAR": {
#         "navigation": 
#         [
#             {
#                 "title": _("Ruangan"),
#                 "separator" : True,
#                 "collapsible": True,
#                 "items": 
#                 [                
#                     {
#                         "title": "Manajemen Ruangan",
#                         "icon": "room_preferences",
#                         "link": reverse_lazy("admin:webapp_room_changelist"), # Format: admin:applabel_modelname_changelist
#                         "collapsible": True,
#                     },
#                     {
#                         "title": "Tipe Ruangan",
#                         "icon": "room_preferences",
#                         "link": reverse_lazy("admin:webapp_roomtype_changelist"), # Format: admin:applabel_modelname_changelist
#                     },
#                     {
#                         "title" : "Fasilitas Ruangan",
#                         "icon": "room_preferences",
#                         "link": reverse_lazy("admin:webapp_facility_changelist"), # Format: admin:applabel_modelname_changelist
#                     },
#                 ],
#                 "title": _("tESTING"),
#                 "separator" : True,
#                 "collapsible": True,
#                 "items" :
#                 [
#                     {
#                         "title": "Fasilitas Ruangan Testing", # Ubah judul agar lebih jelas
#                         "icon": "room_preferences",
#                         "link": reverse_lazy("admin:webapp_facility_changelist"),
#                     },
#                 ],
#                     # Grup untuk Kamar yang bisa diciutkan (collapsible)
#                     # {
#                     #     "title": "Manajemen Kamar",
#                     #     "icon": "hotel",
#                     #     "items": [
#                     #         {
#                     #             "title": "Kamar (Rooms)",
#                     #             "link": "admin:webapp_room_changelist", # Ganti 'webapp' dengan app_label Anda jika berbeda
#                     #         },
#                     #         {
#                     #             "title": "Tipe Kamar (Room Types)",
#                     #             "link": "admin:webapp_roomtype_changelist",
#                     #         },
#                     #         {
#                     #             "title": "Fasilitas (Facilities)",
#                     #             "link": "admin:webapp_facility_changelist",
#                     #         },
#                     #         {
#                     #             "title": "Pemesanan (Bookings)",
#                     #             "link": "admin:webapp_booking_changelist",
#                     #         },
#                     #     ],
#                     # },
#                     # Model lain yang tidak masuk grup
#                     # {
#                     #     "title": "Ulasan (Reviews)",
#                     #     "icon": "thumb-up",
#                     #     "link": "admin:webapp_review_changelist",
#                     # },
                
#             },
#         ],
#     },
# }




# UNFOLD = {
#     "SITE_TITLE": "Dashboard Manahayu",
#     "SITE_HEADER": "Dashboard Manahayu",
#     "SITE_SUBHEADER": "Selamat Datang di Dashboard",
#     # "SITE_ICON": {
#     #     "light": lambda request: static("img/icon-light.svg"),
#     #     "dark": lambda request: static("img/icon-dark.svg"),
#     # },
#     # "SITE_LOGO": lambda request: static("img/my_logo.svg"),
#     # "LOGIN": {
#     #     "image": lambda request: static("img/login-background.jpg"),
#     # },
#     "BORDER_RADIUS": "6px", # Contoh: sudut lebih membulat
#     # "COLORS": {
#     #     "primary": {
#     #         "50": "142 47% 95%",
#     #         "100": "142 47% 88%",
#     #         "200": "142 47% 76%",
#     #         "300": "142 47% 65%",
#     #         "400": "142 47% 56%",
#     #         "500": "142 47% 48%",
#     #         "600": "142 47% 43%",
#     #         "700": "142 47% 38%",
#     #         "800": "142 47% 33%",
#     #         "900": "142 47% 29%",
#     #         "950": "142 47% 18%",
#     #     },
#     #     # ... tambahkan palet warna lain
#     # },
#     "SIDEBAR": {
#         "title": _("Navigation"),
#         "show_search": True,
#         "separator": True,
#         # "collapsible": True,
#         "items":[
#             # {
#             # "title" : _("Dashboard"),
#             # "icon" : "dashboard",
#             # "link" : reverse_lazy("admin:index"),
#             # "badge" : "Main"
#             # # "permision" : lambda request: request.user.is_superuser
#             # },
#             {
#             "title": _("Booking"),
#             "icon": "local_shipping",
#             "link" : reverse_lazy("admin:webapp_booking_changelist")
#             }
#         ]


#     },
#     # "STYLES": [
#     #     lambda request: static("css/custom.css"), # Tambahkan CSS kustom Anda
#     # ],
#     # "SCRIPTS": [
#     #     lambda request: static("js/custom.js"), # Tambahkan JS kustom Anda
#     # ],
#     # ... opsi konfigurasi lainnya
# }
























# settings.py
UNFOLD = {
    "SITE_TITLE": "Dashboard Manahayu",
    "SITE_HEADER": "Dashboard Manahayu",
    "SITE_SUBHEADER": "Selamat Datang di Dashboard",
    "SITE_ICON": {
        "light": lambda request: static("img/manahayu.png"),
        "dark": lambda request: static("img/manahayu.png"),
    },
    "LOGIN": {
        #  "image": lambda request: static("img/my_logo.jpg"),
    },

    "COLORS": {
        "primary": {
           # Ini adalah shade kuning keemasan.
            "50": "50 90% 90%",   # Lebih redup dari sebelumnya
            "100": "50 85% 85%",
            "200": "50 80% 75%",
            "300": "50 75% 65%",
            "400": "50 70% 55%",
            "500": "50 65% 45%",  # Ini akan menjadi warna utama Anda, lebih gelap
            "600": "50 60% 40%",
            "700": "50 55% 35%",
            "800": "50 50% 30%",
            "900": "50 45% 25%",
            "950": "50 40% 20%",  # Lebih gelap
        },
        # Anda juga bisa mendefinisikan palet warna lain di sini (misalnya "secondary")
    },
    "SIDEBAR": {
        "show_search": True, # Opsi lain di sidebar
        "show_all_applications": False,
        "icon": "room_preferences",
        "navigation": [ # <-- Ini adalah daftar untuk navigasi kustom Anda
            {
                "title": _("Ruangan"), # Grup kustom "Ruangan"
                "separator" : True,
                "collapsible": True,
                "icon": "room_preferences",
                "items": [
                    {
                        "title": "Manajemen Ruangan",
                        "icon": "room_preferences",
                        "link": reverse_lazy("admin:webapp_room_changelist"),
                    },
                    {
                        "title": "Tipe Ruangan",
                        "icon": "linked_services",
                        "link": reverse_lazy("admin:webapp_roomtype_changelist"),
                    },
                    {
                        "title" : "Fasilitas Ruangan",
                        "icon": "category",
                        "link": reverse_lazy("admin:webapp_facility_changelist"),
                    },
                    {
                        "title" : "Booking Ruangan",
                        "icon": "event",
                        "link": reverse_lazy("admin:webapp_booking_changelist"),
                    },
                ],
            },
            # Anda bisa menambahkan grup kustom lain di sini
            {
                "title": _("Menu"), # Judul grup baru untuk item tunggal
                "separator": True, # Tidak perlu separator jika hanya beberapa item
                "collapsible": True, # Tidak perlu collapsible jika hanya beberapa item
                "items": [
                    {
                        "title": _("Katalog Menu"),
                        "icon": "restaurant",
                        "link": reverse_lazy("admin:webapp_menu_changelist"),
                    },
                    {
                        "title": _("Kategori Menu"),
                        # "icon": "category",
                        "icon": "concierge",
                        "link": reverse_lazy("admin:webapp_category_changelist"),
                    },
                ],
            },
            {
                "title": _("Paket"), # Judul grup baru untuk item tunggal
                "separator": True, # Tidak perlu separator jika hanya beberapa item
                "collapsible": True, # Tidak perlu collapsible jika hanya beberapa item
                "items":[
                    {
                        "title": _("Manajemen Paket"),
                        "icon": "confirmation_number",
                        "link": reverse_lazy("admin:webapp_package_changelist"),
                    },  
                    {
                        "title": _("Fasilitas Paket"),
                        "icon": "view_list",
                        "link": reverse_lazy("admin:webapp_servicefeature_changelist"),
                    },  
                    {
                        "title": _("Booking Paket"),
                        "icon": "event",
                        "link": reverse_lazy("admin:webapp_reservation_changelist"),
                    },  
                ]
            },
            {
                "title": _("Lain - lain"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Manajemen Pesan"),
                        "icon": "call_log", # Icon grup pengguna
                        "link": reverse_lazy("admin:webapp_contact_changelist"),
                    },
                    {
                        "title": _("Nomor Whatsapp"),
                        "icon": "phone", # Icon grup pengguna
                        "link": reverse_lazy("admin:webapp_maincontact_changelist"),
                    },
                    {
                        "title": _("Review"),
                        "icon": "hotel_class", # Icon grup pengguna
                        "link": reverse_lazy("admin:webapp_review_changelist"),
                    },
                    {
                        "title": _("Users"),
                        "icon": "person", # Icon pengguna tunggal
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "groups", # Icon grup pengguna
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            }  
        ],
    },

}
















