# Generated by Django 5.2.1 on 2025-05-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fa-solid fa-bed)', max_length=50, null=True),
        ),
    ]
