# Generated by Django 5.2.1 on 2025-05-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_menu_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
