# Generated by Django 5.2.1 on 2025-06-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_facility_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='type', to='webapp.roomtype'),
        ),
    ]
