# Generated by Django 5.2.2 on 2025-06-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Main Contact',
                'verbose_name_plural': 'Main Contact',
            },
        ),
    ]
