# Generated by Django 5.2.2 on 2025-06-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_maincontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(related_name='bookings', to='webapp.room'),
        ),
    ]
