# Generated by Django 5.2.2 on 2025-06-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_reservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_in_time',
        ),
    ]
